use("IEI_N3_C1");

db.usuarios.insertMany([
{
    nombre: "Juan González Pérez",
    rut: "12345678-5",
    correo: "juan.gonzalez@correo.cl",
    email: "juan.gonzalez@correo.cl",
    telefono: "912345678",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1990-03-15"),
    direccion: { comuna: "Las Condes", calle: "Av. Apoquindo", numero: "1234", departamento: "101" },
    contrasena: "Password123!"
},
{
    nombre: "María Soto Rojas",
    rut: "9876543-3",
    correo: "maria.soto@correo.cl",
    email: "maria.soto@correo.cl",
    telefono: "912345679",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1992-07-21"),
    direccion: { comuna: "Providencia", calle: "Calle Príncipe de Gales", numero: "4321", departamento: "202" },
    contrasena: "Password123!"
},
{
    nombre: "Pedro Muñoz Silva",
    rut: "14567890-0",
    correo: "pedro.munoz@correo.cl",
    email: "pedro.munoz@correo.cl",
    telefono: "912345680",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1988-11-10"),
    direccion: { comuna: "Ñuñoa", calle: "Irarrázaval", numero: "5566", departamento: "303" },
    contrasena: "Password123!"
},
{
    nombre: "Ana Contreras Díaz",
    rut: "16789012-7",
    correo: "ana.contreras@correo.cl",
    email: "ana.contreras@correo.cl",
    telefono: "912345681",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1995-01-08"),
    direccion: { comuna: "Santiago", calle: "Alameda", numero: "1000", departamento: "405" },
    contrasena: "Password123!"
},
{
    nombre: "Diego Morales Torres",
    rut: "17890123-7",
    correo: "diego.morales@correo.cl",
    email: "diego.morales@correo.cl",
    telefono: "912345682",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1991-05-12"),
    direccion: { comuna: "Vitacura", calle: "Cerro El Plomo", numero: "789", departamento: "506" },
    contrasena: "Password123!"
},
{
    nombre: "Camila Fuentes López",
    rut: "18901234-6",
    correo: "camila.fuentes@correo.cl",
    email: "camila.fuentes@correo.cl",
    telefono: "912345683",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1997-08-19"),
    direccion: { comuna: "La Florida", calle: "San Diego", numero: "234", departamento: "607" },
    contrasena: "Password123!"
},
{
    nombre: "Felipe Hernández Araya",
    rut: "19012345-5",
    correo: "felipe.hernandez@correo.cl",
    email: "felipe.hernandez@correo.cl",
    telefono: "912345684",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1987-09-24"),
    direccion: { comuna: "Maipú", calle: "Av. Pajaritos", numero: "987", departamento: "708" },
    contrasena: "Password123!"
},
{
    nombre: "Valentina Flores Espinoza",
    rut: "20123456-4",
    correo: "valentina.flores@correo.cl",
    email: "valentina.flores@correo.cl",
    telefono: "912345685",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1998-02-11"),
    direccion: { comuna: "Peñalolén", calle: "Av. Grecia", numero: "321", departamento: "809" },
    contrasena: "Password123!"
},
{
    nombre: "José Valenzuela Martínez",
    rut: "21234567-3",
    correo: "jose.valenzuela@correo.cl",
    email: "jose.valenzuela@correo.cl",
    telefono: "912345686",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1993-04-17"),
    direccion: { comuna: "Quilicura", calle: "Av. Recoleta", numero: "456", departamento: "901" },
    contrasena: "Password123!"
},
{
    nombre: "Daniela Rodríguez Pérez",
    rut: "22345678-2",
    correo: "daniela.rodriguez@correo.cl",
    email: "daniela.rodriguez@correo.cl",
    telefono: "912345687",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1994-10-22"),
    direccion: { comuna: "La Reina", calle: "Tobalaba", numero: "678", departamento: "102" },
    contrasena: "Password123!"
},
{
    nombre: "Ignacio Silva González",
    rut: "23456789-1",
    correo: "ignacio.silva@correo.cl",
    email: "ignacio.silva@correo.cl",
    telefono: "912345688",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1989-06-03"),
    direccion: { comuna: "Macul", calle: "Av. Vicuña Mackenna", numero: "901", departamento: "203" },
    contrasena: "Password123!"
},
{
    nombre: "Catalina Rojas Muñoz",
    rut: "13579135-5",
    correo: "catalina.rojas@correo.cl",
    email: "catalina.rojas@correo.cl",
    telefono: "912345689",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1996-12-07"),
    direccion: { comuna: "Pudahuel", calle: "Av. San Pablo", numero: "112", departamento: "304" },
    contrasena: "Password123!"
},
{
    nombre: "Tomás Díaz Soto",
    rut: "24680246-8",
    correo: "tomas.diaz@correo.cl",
    email: "tomas.diaz@correo.cl",
    telefono: "912345690",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1990-09-30"),
    direccion: { comuna: "San Miguel", calle: "Av. José Miguel Carrera", numero: "215", departamento: "405" },
    contrasena: "Password123!"
},
{
    nombre: "Martina Pérez Contreras",
    rut: "15791357-1",
    correo: "martina.perez@correo.cl",
    email: "martina.perez@correo.cl",
    telefono: "912345691",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1999-03-28"),
    direccion: { comuna: "Ñuñoa", calle: "Irarrázaval", numero: "774", departamento: "506" },
    contrasena: "Password123!"
},
{
    nombre: "Benjamín Torres Morales",
    rut: "26802468-4",
    correo: "benjamin.torres@correo.cl",
    email: "benjamin.torres@correo.cl",
    telefono: "912345692",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1992-01-13"),
    direccion: { comuna: "Santiago", calle: "San Antonio", numero: "111", departamento: "607" },
    contrasena: "Password123!"
},
{
    nombre: "Francisca Espinoza Fuentes",
    rut: "17913579-7",
    correo: "francisca.espinoza@correo.cl",
    email: "francisca.espinoza@correo.cl",
    telefono: "912345693",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1995-11-18"),
    direccion: { comuna: "Providencia", calle: "Pedro de Valdivia", numero: "522", departamento: "708" },
    contrasena: "Password123!"
},
{
    nombre: "Andrés Martínez Hernández",
    rut: "28024680-0",
    correo: "andres.martinez@correo.cl",
    email: "andres.martinez@correo.cl",
    telefono: "912345694",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1988-08-26"),
    direccion: { comuna: "Las Condes", calle: "Av. Apoquindo", numero: "1300", departamento: "809" },
    contrasena: "Password123!"
},
{
    nombre: "Javiera Araya Flores",
    rut: "19135791-3",
    correo: "javiera.araya@correo.cl",
    email: "javiera.araya@correo.cl",
    telefono: "912345695",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1997-06-14"),
    direccion: { comuna: "La Florida", calle: "Vicuña Mackenna", numero: "2200", departamento: "902" },
    contrasena: "Password123!"
},
{
    nombre: "Vicente López Valenzuela",
    rut: "20246802-5",
    correo: "vicente.lopez@correo.cl",
    email: "vicente.lopez@correo.cl",
    telefono: "912345696",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1991-04-02"),
    direccion: { comuna: "Peñalolén", calle: "Av. Grecia", numero: "334", departamento: "103" },
    contrasena: "Password123!"
},
{
    nombre: "Antonia González Silva",
    rut: "11357913-8",
    correo: "antonia.gonzalez@correo.cl",
    email: "antonia.gonzalez@correo.cl",
    telefono: "912345697",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("2000-07-09"),
    direccion: { comuna: "Macul", calle: "Av. Grecia", numero: "448", departamento: "204" },
    contrasena: "Password123!"
},
{
    nombre: "Paula Muñoz Rodríguez",
    rut: "22468024-1",
    correo: "paula.munoz@correo.cl",
    email: "paula.munoz@correo.cl",
    telefono: "912345698",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1993-02-20"),
    direccion: { comuna: "Maipú", calle: "Av. Pajaritos", numero: "515", departamento: "305" },
    contrasena: "Password123!"
},
{
    nombre: "Sebastián Soto Flores",
    rut: "13579124-0",
    correo: "sebastian.soto@correo.cl",
    email: "sebastian.soto@correo.cl",
    telefono: "912345699",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1989-12-01"),
    direccion: { comuna: "Quilicura", calle: "Av. Recoleta", numero: "221", departamento: "406" },
    contrasena: "Password123!"
},
{
    nombre: "Carolina Díaz Araya",
    rut: "24680235-7",
    correo: "carolina.diaz@correo.cl",
    email: "carolina.diaz@correo.cl",
    telefono: "912345700",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1996-05-05"),
    direccion: { comuna: "Santiago", calle: "Av. Libertador Bernardo O'Higgins", numero: "345", departamento: "507" },
    contrasena: "Password123!"
},
{
    nombre: "Matías Fuentes Torres",
    rut: "15791346-6",
    correo: "matias.fuentes@correo.cl",
    email: "matias.fuentes@correo.cl",
    telefono: "912345701",
    generoString: "M",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1994-08-16"),
    direccion: { comuna: "La Reina", calle: "Av. Ossa", numero: "223", departamento: "608" },
    contrasena: "Password123!"
},
{
    nombre: "Fernanda Hernández Espinoza",
    rut: "26802457-3",
    correo: "fernanda.hernandez@correo.cl",
    email: "fernanda.hernandez@correo.cl",
    telefono: "912345702",
    generoString: "F",
    nacionalidad: "CL",
    fechaNacimiento: ISODate("1998-10-27"),
    direccion: { comuna: "Vitacura", calle: "Av. Kennedy", numero: "778", departamento: "709" },
    contrasena: "Password123!"
}
]);